on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }} 
          passphrase: ${{ secrets.PRODUCTION_PASSPHRASE }}
          script: |
            cd /var/www/mrwhale.io/mrwhale
            git pull origin master
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/bin/node"
            sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/pm2" "/usr/local/bin/pm2"
            yarn install && yarn run build
            pm2 reload all
